name: 'Deploy to my Dokku instance'

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
  
    - name: Cloning repo # This step is required
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # This is required or you might get an error from Dokku

    - name: Push to dokku
      uses: obrassard/action-dokku-deploy@v1.0.3
      with:
        dokku_repo: 'ssh://dokku@192.248.164.119/dev-docs'
        ssh_key: ${{ secrets.SSH_KEY }}
        deploy_branch: 'main'
