name: Deploy to Dokku
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy to Dokku
    runs-on: ubuntu-22.04
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Setup ssh access
      run: |
        set -x
        mkdir -p ~/.ssh
        eval `ssh-agent -s`
        ssh-add - <<< "${{ secrets.SSH_KEY }}"
        ssh-keyscan ${{ secrets.DOKKU_IP_ADDRESS }}>> ~/.ssh/known_hosts
    - name: Pull new site
      run: |
        set -x
        eval `ssh-agent -s`
        ssh-add - <<< "${{ secrets.SSH_KEY}}"
        echo Creating dokku app dev-docs
        ssh ${{ secrets.DOKKU_HOST }}@${{ secrets.DOKKU_IP_ADDRESS }} -C "dokku apps:create dev-docs" | true
        ssh ${{ secrets.DOKKU_HOST }}@${{ secrets.DOKKU_IP_ADDRESS }} -C "dokku git:initialize dev-docs"
        ssh ${{ secrets.DOKKU_HOST }}@${{ secrets.DOKKU_IP_ADDRESS }} -C "dokku git:sync --build dev-docs" https://github.com/Subscribie/dev-docs.git main
        ssh ${{ secrets.DOKKU_HOST }}@${{ secrets.DOKKU_IP_ADDRESS }} -C "dokku config:set --no-restart dev-docs DOKKU_LETSENCRYPT_EMAIL=${{ secrets.LETSENCRYPT_EMAIL }}"
        ssh ${{ secrets.DOKKU_HOST }}@${{ secrets.DOKKU_IP_ADDRESS }} -C "dokku letsencrypt:enable dev-docs"
        ssh ${{ secrets.DOKKU_HOST }}@${{ secrets.DOKKU_IP_ADDRESS }} -C "dokku letsencrypt:cron-job --add"
